### ISSUE TITLE
Getting error Field not found: 'RabbitMQ.Client.ConnectionFactory.RequestedHeartbeat'.

### ISSUE THREAD

**Issue by isaacllopisaracil** [tenor/RestBus#2]
When using RabbitMQ.Client NuGet package version 3.2.1 it works fine, but if updated, the RestBusSubscriber constructor fails with message:

Field not found: 'RabbitMQ.Client.ConnectionFactory.RequestedHeartbeat'.

It seems this field is no longer there in RabbitMQ.Client.ConnectionFactory.
Would it not be better for the developer to set these things?

**Comment by tenor** [comment]
Resolved by 85ee51b5cc979e503b5634bb06eb57553a471a4f
